### ISSUE TITLE
Notes gehen ned

### ISSUE THREAD

**Issue by jaegerndorferfan1** [quokkah/Consolas#1]
Wenn ich note erstellen will dann name eingeben soll und enter drücke, dann passiert nix. Ich komm nur mit -back zurück

**Comment by quokkah** [comment]
Sehr geehrter Kunde,
wir möchten uns aufrichtig für die Unannehmlichkeiten entschuldigen, die Ihnen durch den Fehler in unserem Java-Programm entstanden sind. Es ist unser Ziel, qualitativ hochwertige Software zu liefern, und es bedauert uns zutiefst, dass diesmal ein Fehler aufgetreten ist.
Wir verstehen, dass Zuverlässigkeit ein Schlüsselfaktor bei der Nutzung unserer Produkte ist, und es ist klar, dass wir in diesem Fall Ihre Erwartungen nicht erfüllen konnten. Bitte seien Sie versichert, dass unser Entwicklerteam bereits mit Hochdruck daran arbeitet, das Problem zu identifizieren und zu beheben.
In der Zwischenzeit stehen wir Ihnen für jegliche Unterstützung zur Verfügung und werden Sie umgehend informieren, sobald das Update verfügbar ist. Wir schätzen Ihr Vertrauen in unsere Produkte und bitten Sie, uns die Gelegenheit zu geben, das Problem zu korrigieren und Ihre Zufriedenheit sicherzustellen.
Mit freundlichen Grüßen, Ihr [Firmenname]-Team
